language: python
python:
  - "2.7"
install: "pip install sphinx_rtd_theme git+https://github.com/changux/sphinxcontrib-images.git"
script: 
  - make html
  - sudo pip install s3cmd
  - s3cmd sync --delete-removed -P -M -r build/html s3://doc-data-wazuh
