language: python
python:
  - "2.7"
install: "pip install sphinx_rtd_theme git+https://github.com/changux/sphinxcontrib-images.git"
script: 
  - make html
  - git clone https://github.com/perfectsense/travis-s3-deploy.git && sh deploy.sh
