language: python
python:
  - "2.7"
install: "pip install sphinx_rtd_theme git+https://github.com/changux/sphinxcontrib-images.git"
script: make html
addons:
  artifacts: true
  debug: true
  s3_region: "us-east-2" 
    paths:
     - $(git ls-files -o | grep 'build/html' | tr "\n" ":")
